import "./globals.css";
import { Inter } from "next/font/google";
import { SharedLayout } from "@/exports";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <SharedLayout>{children}</SharedLayout>
        </Providers>
      </body>
    </html>
  );
}
