import "./globals.css";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { SharedLayout } from "@/exports";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'],})

export const metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakarta.className} bg-grayscale-50 dark:bg-stone-950 `}>
        <Providers>
          <SharedLayout>{children}</SharedLayout>
        </Providers>
      </body>
    </html>
  );
}
